.PHONY: clean All

All:
	@echo "----------Building project:[ stack - Debug ]----------"
	@cd "stack" && "$(MAKE)" -f  "stack.mk"
clean:
	@echo "----------Cleaning project:[ stack - Debug ]----------"
	@cd "stack" && "$(MAKE)" -f  "stack.mk" clean
